name: Build VS2017 Project

on: [push]

jobs:
  build:
    runs-on: windows-2019  # Contains VS 2017/2019 build tools

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet Packages
      run: nuget restore

    - name: Build Solution
      # Replace 'YourSolutionName.sln' with the actual .sln file name in the repo
      run: msbuild Borderless-Gaming.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Game
        path: |
          **\bin\Release\**\*.exe
          **\bin\Release\**\*.dll
